timeout: "120000"
spec:
  - core/*/test/**/*.test.ts
  - plugin/*/test/**/*.test.ts
  - standalone/*/test/**/*.test.ts
recursive: true
extension:
  - ts
require:
  - intelli-espower-loader
  - source-map-support/register
  - espower-typescript/guess
full-trace: true
exit: true
