export const enum HTTPMethodEnum {
  GET = 'GET',
  POST = 'POST',
  DELETE = 'DELETE',
  PUT = 'PUT',
}

export const HOOK_HTTP_META_PREFIX = 'TEGG#HOOK_HTTP_META_PREFIX::';
export const HOOK_MIDDLEWARE_META_PREFIX = 'TEGG#HOOK_MIDDLEWA_META_PREFIX::';
export const HOOK_CONTROLLER_PARAMS_PREFIX = 'TEGG#HOOK_CONTROLLER_PARAMS_PREFIX::';

export const ORIGIN_SERVER = 'TEGG::ORIGIN_SERVER';
export const KOA_APPLICATION = 'TEGG::ORIGIN_KOA_APPLICATION';
export const KOA_ROUTER = 'TEGG::KOA_ROUTER';
export const KOA_CONTEXT = 'TEGG::KOA_CONTEXT';

export const TEGG_CONTEXT = 'TEGG::CONTEXT';
export const TEGG_OUTPUT = 'TEGG::OUTPUT';
export const TEGG_ROUTER = 'TEGG::ROUTER';

export const REQUEST = 'TEGG::REQUEST';
export const RESPONSE = 'TEGG::RESPONSE';
export const PARAMS = 'TEGG::PARAMS';
export const QUERY = 'TEGG::QUERY';
export const BODY = 'TEGG::BODY';
